  
image:
  - Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

branches:
  only:
    - main
    - develop

test: off
build: off

environment:
  COVERALLS_REPO_TOKEN:
    secure: KSl6wuSAIFW0emX3EYOC0t1Bz1EYtTZurccG2R3O0jWP0CeNF221zR4fBr0MlLSw
  CODECOV_REPO_TOKEN:
    secure: ZJuIZ8w5gxAhkRmMt7lJ9JPRsg/im571KK4q8f84S9ML9DWTr+W7wxc+BmI06Trq
  MYGET_API_KEY:
    secure: j6rYrax7Ms3Fv7zDkX00i4KhKerBX7ZPT2zwicsz79V/kZpoGwwXMZvb2zqdoa/d
  MYGET_SOURCE: https://www.myget.org/F/nils-org/api/v2/package
  WYAM_DEPLOY_REMOTE: https://github.com/nils-org/XmlComparer.git
  WYAM_DEPLOY_BRANCH: gh-pages
  WYAM_ACCESS_TOKEN:
    secure: 27NrybgoeU+CIo1RL4x3JYwQwqkeQXr8CpRLm6lp4ElhgWS4T5spWm3mqMFYyEhI
  GITHUB_USERNAME: nils-a
  GITHUB_PASSWORD:
    secure: 27NrybgoeU+CIo1RL4x3JYwQwqkeQXr8CpRLm6lp4ElhgWS4T5spWm3mqMFYyEhI
  #NUGET_API_KEY:
  #  secure: u5B6dH7j3Jhsiu4VXD7uZDFrGHKCZC9DL2ahqyopCUGG/t7kTnecQVNxjeFnTluu
  #NUGET_SOURCE: https://api.nuget.org/v2/package
  

build_script:
  - ps: .\build.ps1 -Target AppVeyor -Verbosity Diagnostic

cache:
  - "tools -> recipe.cake,tools/packages.config"